package com.app.sifanggou.net;

import com.app.sifanggou.net.httprunner.AddBusinessBuyShelfNumHttpRunner;
import com.app.sifanggou.net.httprunner.AddBusinessCommodityCollectHttpRunner;
import com.app.sifanggou.net.httprunner.AddBusinessCommodityHttpRunner;
import com.app.sifanggou.net.httprunner.AddBusinessDefaultDeliverAddressHttpRunner;
import com.app.sifanggou.net.httprunner.AddBusinessDeliverAddressHttpRunner;
import com.app.sifanggou.net.httprunner.AddBusinessPartnerHttpRunner;
import com.app.sifanggou.net.httprunner.AddBusinessPrintConfigHttpRunner;
import com.app.sifanggou.net.httprunner.AddBusinessShoppingCartHttpRunner;
import com.app.sifanggou.net.httprunner.AddBusinessStaffHttpRunner;
import com.app.sifanggou.net.httprunner.AddBusinessUrgentSellCommodityHttpRunner;
import com.app.sifanggou.net.httprunner.BatchUpdateCommodityShelfStatusHttpRunner;
import com.app.sifanggou.net.httprunner.BusinessChangePasswordHttpRunner;
import com.app.sifanggou.net.httprunner.BusinessLoginHttpRunner;
import com.app.sifanggou.net.httprunner.BusinessRegistHttpRunner;
import com.app.sifanggou.net.httprunner.BusinessSubmitOrderHttpRunner;
import com.app.sifanggou.net.httprunner.DelBusinessCommodityCollectHttpRunner;
import com.app.sifanggou.net.httprunner.DelBusinessDeliverAddressHttpRunner;
import com.app.sifanggou.net.httprunner.DelBusinessPartnerHttpRunner;
import com.app.sifanggou.net.httprunner.DelBusinessShoppingCartHttpRunner;
import com.app.sifanggou.net.httprunner.DelBusinessStaffHttpRunner;
import com.app.sifanggou.net.httprunner.GetAgentLevelInfoHttpRunner;
import com.app.sifanggou.net.httprunner.GetAliyunstsTokenHttpRunner;
import com.app.sifanggou.net.httprunner.GetAllBusinessUrgentSellCommodityHttpRunner;
import com.app.sifanggou.net.httprunner.GetBusinenessInOutOrderInfoHttpRunner;
import com.app.sifanggou.net.httprunner.GetBusinenessOrderInfoSpecialStatusHttpRunner;
import com.app.sifanggou.net.httprunner.GetBusinessCanAllocateShelfNumHttpRunner;
import com.app.sifanggou.net.httprunner.GetBusinessCommodityByCategoryCodeHttpRunner;
import com.app.sifanggou.net.httprunner.GetBusinessCommodityCollectHttpRunner;
import com.app.sifanggou.net.httprunner.GetBusinessCommodityInfo2HttpRunner;
import com.app.sifanggou.net.httprunner.GetBusinessCommodityInfoHttpRunner;
import com.app.sifanggou.net.httprunner.GetBusinessConcernedInfoHttpRunner;
import com.app.sifanggou.net.httprunner.GetBusinessDefaultDeliverAddressHttpRunner;
import com.app.sifanggou.net.httprunner.GetBusinessDeliverAddressHttpRunner;
import com.app.sifanggou.net.httprunner.GetBusinessInfoByCodeHttpRunner;
import com.app.sifanggou.net.httprunner.GetBusinessInfoHttpRunner;
import com.app.sifanggou.net.httprunner.GetBusinessInviteCodeHttpRunner;
import com.app.sifanggou.net.httprunner.GetBusinessPartnerHttpRunner;
import com.app.sifanggou.net.httprunner.GetBusinessRongYunTokenHttpRunner;
import com.app.sifanggou.net.httprunner.GetBusinessShoppingCartListHttpRunner;
import com.app.sifanggou.net.httprunner.GetBusinessStaffInfoHttpRunner;
import com.app.sifanggou.net.httprunner.GetBusinessUrgentSellCommoditHttpRunner;
import com.app.sifanggou.net.httprunner.GetCityMarketHttpRunner;
import com.app.sifanggou.net.httprunner.GetCommodityInfoByIdHttpRunner;
import com.app.sifanggou.net.httprunner.GetCommodityTypeListHttpRunner;
import com.app.sifanggou.net.httprunner.GetFirstPageAdHttpRunner;
import com.app.sifanggou.net.httprunner.GetProvinceCityZoneHttpRunner;
import com.app.sifanggou.net.httprunner.GetRecommendCommodityHttpRunner;
import com.app.sifanggou.net.httprunner.GetShelfAmountHttpRunner;
import com.app.sifanggou.net.httprunner.GetVerInfoHttpRunner;
import com.app.sifanggou.net.httprunner.GetVerifyCodeHttpRunner;
import com.app.sifanggou.net.httprunner.IsBusinessCollectCommodityHttpRunner;
import com.app.sifanggou.net.httprunner.IsBusinessPartnerHttpRunner;
import com.app.sifanggou.net.httprunner.SearchBusinessCommodityOnNameHttpRunner;
import com.app.sifanggou.net.httprunner.SerachBusinessOnNameHttpRunner;
import com.app.sifanggou.net.httprunner.UpdateBusinessCommodityHttpRunner;
import com.app.sifanggou.net.httprunner.UpdateBusinessDeliverAddressHttpRunner;
import com.app.sifanggou.net.httprunner.UpdateBusinessInfoHttpRunner;
import com.app.sifanggou.net.httprunner.UpdateBusinessOrderStatusHttpRunner;
import com.app.sifanggou.net.httprunner.UpdateBusinessShoppingCartCommodityNumHttpRunner;
import com.app.sifanggou.net.httprunner.UpdateCommodityPriceHttpRunner;

public class NetUtils {
	
	public static void init() {
		final AndroidEventManager eventManager = AndroidEventManager.getInstance();
		eventManager.registerEventRunner(EventCode.HTTP_GETVERIFYCODE, new GetVerifyCodeHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETPROVINCECITYZONE, new GetProvinceCityZoneHttpRunner()); 
		eventManager.registerEventRunner(EventCode.HTTP_GETCITYMARKET, new GetCityMarketHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETALIYUNSTSTOKEN, new GetAliyunstsTokenHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_BUSINESSREGIST, new BusinessRegistHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETAGENTLEVELINFO, new GetAgentLevelInfoHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_BUSINESSLOGIN, new BusinessLoginHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_BUSINESSCHANGEPASSWORD, new BusinessChangePasswordHttpRunner());
        eventManager.registerEventRunner(EventCode.HTTP_GETBUSINESSCANALLOCATESHELFNUM, new GetBusinessCanAllocateShelfNumHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETSHELFAMOUNT, new GetShelfAmountHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_ADDBUSINESSBUYSHELFNUM, new AddBusinessBuyShelfNumHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETCOMMODITYTYPELIST, new GetCommodityTypeListHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_ADDBUSINESSCOMMODITY, new AddBusinessCommodityHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETBUSINESSCOMMODITYINFO, new GetBusinessCommodityInfoHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_BATCHUPDATECOMMODITYSHELFSTATUS, new BatchUpdateCommodityShelfStatusHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_UPDATECOMMODITYPRICE, new UpdateCommodityPriceHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETBUSINESSURGENTSELLCOMMODIT, new GetBusinessUrgentSellCommoditHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_ADDBUSINESSURGENTSELLCOMMODITY, new AddBusinessUrgentSellCommodityHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_SERACHBUSINESSONNAME, new SerachBusinessOnNameHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_SEARCHBUSINESSCOMMODITYONNAME, new SearchBusinessCommodityOnNameHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_UPDATEBUSINESSSHOPPINGCARTCOMMODITYNUM, new UpdateBusinessShoppingCartCommodityNumHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_ADDBUSINESSSHOPPINGCART, new AddBusinessShoppingCartHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_DELBUSINESSSHOPPINGCART, new DelBusinessShoppingCartHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETBUSINESSSHOPPINGCARTLIST, new GetBusinessShoppingCartListHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETBUSINESSDELIVERADDRESS, new GetBusinessDeliverAddressHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_ADDBUSINESSDELIVERADDRESS, new AddBusinessDeliverAddressHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_DELBUSINESSDELIVERADDRESS, new DelBusinessDeliverAddressHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_UPDATEBUSINESSDELIVERADDRESS, new UpdateBusinessDeliverAddressHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_BUSINESSSUBMITORDER, new BusinessSubmitOrderHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETBUSINENESSORDERINFOSPECIALSTATUS, new GetBusinenessOrderInfoSpecialStatusHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETBUSINENESSINOUTORDERINFO, new GetBusinenessInOutOrderInfoHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETBUSINENESSINOUTORDERINFO_DAJIE, new GetBusinenessInOutOrderInfoHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETBUSINENESSINOUTORDERINFO_DAISHOU, new GetBusinenessInOutOrderInfoHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_UPDATEBUSINESSORDERSTATUS, new UpdateBusinessOrderStatusHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETFIRSTPAGEAD, new GetFirstPageAdHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETBUSINESSCOMMODITYBYCATEGORYCODE, new GetBusinessCommodityByCategoryCodeHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_ADDBUSINESSCOMMODITYCOLLECT, new AddBusinessCommodityCollectHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_ADDBUSINESSPARTNER, new AddBusinessPartnerHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETBUSINESSCOMMODITYCOLLECT, new GetBusinessCommodityCollectHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETBUSINESSPARTNER, new GetBusinessPartnerHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETBUSINESSINVITECODE, new GetBusinessInviteCodeHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_ADDBUSINESSSTAFF, new AddBusinessStaffHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETBUSINESSSTAFFINFO, new GetBusinessStaffInfoHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_ADDBUSINESSPRINTCONFIG, new AddBusinessPrintConfigHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETBUSINESSRONGYUNTOKEN, new GetBusinessRongYunTokenHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETBUSINESSINFO, new GetBusinessInfoHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETALLBUSINESSURGENTSELLCOMMODITY, new GetAllBusinessUrgentSellCommodityHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_ISBUSINESSCOLLECTCOMMODITY, new IsBusinessCollectCommodityHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_DELBUSINESSCOMMODITYCOLLECT, new DelBusinessCommodityCollectHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_ISBUSINESSPARTNER, new IsBusinessPartnerHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_DELBUSINESSPARTNER, new DelBusinessPartnerHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_UPDATEBUSINESSCOMMODITY, new UpdateBusinessCommodityHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_ADDBUSINESSDEFAULTDELIVERADDRESS, new AddBusinessDefaultDeliverAddressHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETBUSINESSDEFAULTDELIVERADDRESS, new GetBusinessDefaultDeliverAddressHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETRECOMMENDCOMMODITY, new GetRecommendCommodityHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_UPDATEBUSINESSINFO, new UpdateBusinessInfoHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETBUSINESSINFOBYCODE, new GetBusinessInfoByCodeHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETCOMMODITYINFOBYID, new GetCommodityInfoByIdHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_DELBUSINESSSTAFF, new DelBusinessStaffHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETBUSINESSCOMMODITYINFO2, new GetBusinessCommodityInfo2HttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETBUSINESSCONCERNEDINFO, new GetBusinessConcernedInfoHttpRunner());
		eventManager.registerEventRunner(EventCode.HTTP_GETVERINFO, new GetVerInfoHttpRunner());
	}
}


